### PR TITLE
NeXus Ontology v2.0

### PR DESCRIPTION
**Pull request by sanbrock**
* contains all the concepts for the full NeXus Vocabulary (definitions, groups, fields, attributes)  
* defines and handles DataTyes and UnitCategories  
* supports enumerations and also cardinality (minOccurs/maxOccurs)  
* checks and marks if a referenced concept (definition, group, field, attribute) has been specialised (e.g. docstring added, enumeration modified, new concept added or a cardinality of a referenced concept has been changed)

### CODE REVIEW

**Comment by sanbrock** [comment]
Please find my slides from our meeting [here](https://box.hu-berlin.de/f/25b17d97ecbf4449a2f4/)  
_  
Our last meeting suggested to express the NeXus enumeration items as separate concepts, which can then manually be connected even to external ontologies.  
>Currently enumerations are handled as class restrictions on the actualValue dataproperty.  
E.g.: NXiv_temo/ENTRY/definition **actualValue** _only_ {"NXiv_temp"^^xsd:string}
>>To represent the corresponding restrictions, we could use the **hasValueContainer** object property (as used for restricting the data type), or we could introduce ha new property **hasEnumerationContainer**.   
E.g.:  
NXiv_temo/ENTRY/definition **hasEnumerationContainer** _only_ (NXiv_temo/ENTRY/definition/NXiv_temp-enumertaion)  
NXiv_temo/ENTRY/definition/NXiv_temp-enumertaion **actualValue** _only_ {"NXiv_temp"^^xsd:string}  
In both cases, the assignment of an enumeration string to an object would require the creation of the corresponding enumeration container object first.

**Comment by sanbrock** [comment]
Paul commented after the meeting:  
One point that struck me was your point about measurements and, in particular, about the units.  This reminded me of the [Digital Representation of Units of Measurement (DRUM) project, from CODATA](https://codata.org/initiatives/task-groups/drum/)  
DRUM have produced an [inventory technologies to do with units](https://codata.org/wp-content/uploads/2022/12/DRUM_Units_Inventory_120522.pdf)  
This inventory lists several ontologies for handling units. Perhaps this is of interest.   

> Sandor points, that NeXus actually  
>- defines is own categories with examples (https://manual.nexusformat.org/nxdl-types.html?highlight=unit+categories)  
>- with no proposal for any automatic validation, but  
>- only suggesting the use of Unidata and its **UDUNITS** (https://manual.nexusformat.org/datarules.html#design-units).  
>Note that in our software solution NOMAD at FAIRmat, we would like to understand and be able to work with the units provided with the data objects in the nxs files. These include checking their consistency with the schema definitions, or converting them if we want to compare 2 or more data objects, or if we are searching for data (e.g. within specified rages). For this purpose, we are actually using **PINT**.  
Nice to see that the CODATA's table includes the tools mentioned above. In fact, it lists lots of others including ontologies which will be very interesting when connecting the NeXus Ontology to external world. Note that in the current proposal, we only focused on expressing what is defined in NeXus, and we suggested the modelling of Nexus unit categories as concepts, so later they can eventually be easily connected to external ontologies.  
One question we arrived to was if and what kind of Object Property shall be used for the relationship between the NeXus Unit Categories (like NX_ENERGY) and their given examples (like keV). This can be something NeXus specific, like ‘compatibleTo’, ‘example’, ’suchAs’, ‘like’, or something similar, but note that inside NeXus this is not ment to be checked. Alternatively, a property defined somewhere else could be used, although this is already binding the NeXus Ontology to an external resource which we might not want to push without NIAC’s consents.

**Comment by sanbrock** [comment]
discussions on usable PIDs  
  
An example on how to refer to "beam flux at sample position":  
  
NXDL definitions:
- **NXbeam**  
"Properties of the neutron or X-ray beam at a given location. ..."
-- NXbeam has an optional field NXbeam/flux:  
**has min 0 NXbeam/flux**  "flux incident on beam plane area"
- **NXsample/BEAM**  
"Details of beam incident on sample - used to calculate sample/beam interaction point"
-- **SubClassOf NXbeam** It is a special NXbeam which is a normal NXbeam, but at the SAMPLE! Hence, there is an inherited relationship:
-- **has min 0 NXbeam/flux**  

Conclusions:  
- **NXbeam/flux** (of NXsample/BEAM)  
It is just a normal NXbeam/flux which we happen to  know that (in this case) is at SAMPLE because it is related to NXsample/BEAM  
- Do we want to represent such a specialised NXbeam/flux concept as a separate **NXsample/BEAM/flux**?  
**NXsample/BEAM/flux SubClassOf NXbeam/flux** so it is a specialisation
**NXsample/BEAM has min 0 NXsample/BEAM/flux** an NXsample/BEAM shall have such specialised beam flux 
**NXsample/BEAM has max 0 NXbeam/flux**  and not just a generic one
- Advantage
-- a specialised meaning is represented by a separate concept (class) which is referencable with a unique PID **_NXsample/BEAM/flux_**  
-- without this a relationship should be referenced: _NXbeam/flux_of_NXsample/BEAM_ (which could actually be also written as **_NXsample/BEAM/flux_**)
-- consistency: because such specialised concepts are anyway always created when stated explicitly in an NXDL definition (e.g. when AppDef states what is required). They are created even if no modifications are defined in which case an equivalent concept is created under a different name as a synonym which is used in asserting optionality restrictions).
- Disadvantage
-- it would result in an unnecessary extension of the asserted NeXus vocabulary where different concepts would refer to the same html anchor of the documentation which would not explain at all their specialisation.
-- if PID is stored together with data (like NX_CLASS attribute is attached to all HDF5 groups - although currently NX_CLASS is only referring to the root base_class cited and not necessary the direct superclass), it would limit its usage e.g a data element NXsample/BEAM/flux would not be includable to any other NXbeam groups where where data with a PID NXbeam/flux is expected.  
Note that this is already the situation in NeXus with NXroot/ENTRY (and similarly with NXentry/SUBENTRY) that accepts NX[anyAppDef]/ENTRY and not only NXentry to be included. This is a kind of polymorphism in NeXus that allows accepting not only a specific class, but also its subclasses. To support such polymorphism without the need of specifying the actual subclass requires the flattenability of the base classes and the reservation of fields names, so their meaning could be resolved (apart of specialisation). Note that such automated mechanism (apart of NXentry) is not supported by NeXus, but if a field defined in an appdef below a group citing a base class  needs to be reused elsewhere, it should be first pulled into the definition of the cited base class.

**Comment by sanbrock** [comment]
Also note that currently, a flux value is just a number, or more precisely a field in NeXus. It becomes NXbeam/flux when it is connected to an NXbeam group as a field 'flux'. It will represent the beam flux at sample if its NXbeam group becomes connected to an NXsample group or any other groups (like NXmx/ENTRY/INSTRUMENT/BEAM) where the meaning is specified so. Note that NXbeam group allows the flux description at any place along the beam path including the sample position. Which position is in use can be specified using the subgroup TRANSFORMATIONS and the field depends_on.  
  
Hence, an information corresponding to any new concept, like "**beam flux at sample**" may be harvested from NeXus individuals connected to different NeXus concepts.  
**_A conversion or normalisation step would allow connecting the NeXus ontology to such external concepts/ontologies._**

**Comment by hgoerzig** [comment]
The ontology IRIs change by version. In this way the IRIs can't be used as PIDs. The ontology version has to be in the ontology metadata.
We will need two versions one version should refer to the NeXus definitions version and the other to the version of the code generating the ontology.

**Comment by sanbrock** [comment]
yes, according to our prior exchange in email:  
v1.1, 2.0, 2.1, 3.0 etc are referring to the ontology and how things are modelled. After settling, I would change them rarely.
The definitions’ short hash on the other hand refers to the different versions of the NeXus standard, so the compatibility here is depending on how much the standard changes. Most of the time it is also changing slowly (like something becomes deprecated, etc.).
So by default, I would say that ALL http://purl.org/nexusformat/*/definitions/*/Field/NXsample/temperature are compatible. More precise relationships can be added when a new release is coming out and we know what has actually been changed…
Note that v2.0 is already uses owl:deprecated (where a NeXus concept is marked), and owl:priorVersion, owl:backwardCompatibleWith, owl:incompatibleWith etc. can also be of use.

Note that version info is added also for the case if something goes wrong in an application, so one can dig down and find the root cause and then make a proper fix. Note that this cannot be avoided and without the version info such fixes would become even more cumbersome.

Examples from other ontologies: 
[versioning in OBO](https://obofoundry.org/principles/fp-004-versioning.html )
[W3 - versioning in OWL](https://www.w3.org/2007/OWL/wiki/Ontology_Versions )

---  
on assigning the concept of the vocabulary item **NXsample/temperature-field** of a specific version of the NeXus standard to **http://purl.org/nexusformat/v2.0/definitions/7ca0338/Field/NXsample/temperature**

**Comment by hgoerzig** [comment]
http://purl.org/nexusformat/*/definitions/*/Field/NXsample/temperature  this will not work. According to definition about what aPID is. http://purl.org/nexusformat/*/definitions/*/Field/NXsample/temperature is the IRI that describes the temperature related to a sample, it is describing always the same thing/concept independend of the ontology version. Therefore, the IRI should stay the same in all versions of the ontology if the same thing referred to.
Can you have a look at "Ten simple rules for making a vocabulary FAIR" rule 5:
https://doi.org/10.1371/journal.pcbi.1009041

If we start doing mappings we get in huge trouble if the IRIs change, as the mapping is made based on the IRIs.

**Review by hgoerzig — APPROVED** [review]
I think we need to discuss the concept of versioning later. Now there is the commit string in the version. In the original version we had the versioning following the NeXus releases.

**Pull request merged**
